### ISSUE TITLE
There is a problem in 1.5 version that screen orientation automatic cannot be fullscreen. It will become a narrow screen rather than fullscreen.

### ISSUE THREAD

**Issue by iesvme** [Huczeq/RTSP-Player#3]
Phone: Pixel 2
Android: 10

![微信图片_20210308222848](https://user-images.githubusercontent.com/16969250/110334601-eb202b80-805d-11eb-9e77-9fc717ea6040.jpg)
![微信图片_20210308222854](https://user-images.githubusercontent.com/16969250/110334610-ed828580-805d-11eb-9d1a-4e53fb7bd6cc.jpg)
![微信图片_20210308222839](https://user-images.githubusercontent.com/16969250/110334632-f1160c80-805d-11eb-8aa1-7016510a53fd.jpg)
![微信图片_20210308222950](https://user-images.githubusercontent.com/16969250/110334641-f2dfd000-805d-11eb-8c0d-3cae8fc6668c.jpg)

**Comment by Huczeq** [comment]
Could you try v1.5.1 version: https://github.com/Huczeq/RTSP-Player/releases/download/v1.5.1/app-universal-release.apk
If you have installed the version from the Google Play Store, you will have to uninstall it and install a new one.
Uninstalling the application will delete all data, so we recommend that you export your backup.
As you have Android 10, you will have to manually move the exported file from the backup folder to the root of your storage, because uninstalling the app will delete these files. Then install the update and move the exported file to the backups folder and import backup in application.
